name: Apply Repolinter
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  apply-repolinter:
    name: Apply Repolinter (${{ matrix.repo }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: aperture-science-incorporated/companion-cube
            config: community-plus.yml
          - repo: aperture-science-incorporated/neurotoxin-codes
            config: new-relic-one-catalog-project.json
          - repo: aperture-science-incorporated/turret-schematics
            config: community-plus.yml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Self
        uses: actions/checkout@v2
        with:
          path: ./repo

      - name: Checkout ${{ matrix.repo }}
        uses: actions/checkout@v2
        with:
          path: ./apply
          repository: ${{ matrix.repo }}
          token: ${{ secrets.PERSONAL_TOKEN }}
      
      - name: Run Repolinter
        uses: newrelic/repolinter-action@feat/custom-working-dir
        with:
          directory: ${{ github.workspace }}/apply
          config_file: ${{ github.workspace }}/repo/${{ matrix.config }}
          output_type: issue
          username: prototypicalpro
          repository: ${{ matrix.repo }}
          token: ${{ secrets.PERSONAL_TOKEN }}


